accCheck:
   mainUrl: http://localhost:9999/accCheck
   accountDaySettleStatus: /config/getAccountDaySettleStatus/
   subjectInfo: /config/getSubjectInfo/
   innerAccountIdByBankAccount: /config/getInnerAccountIdByBankAccount/
   innerAccountIdByChannelNo: /config/getInnerAccountIdByChannelNo/
   
#接口访问并发数
service:
  access-max-count: 200

#线程池配置 
thread:
  pool:
    initSize: 50
    maxSize: 100
    waitQueueSize: 1000  
